version: "3"
services:
  mongodb:    
    image: mongo:4.2.0   
    container_name: mongo_db
    volumes:
      - ./data:/data 
  app1:
    build: app
    image: node_app
    container_name: app1
    ports:
      - "3000"
    command: npm run start
    environment:
      DEBUG: 1
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017 
    volumes:
      - ./app:/src
      - /src/node_modules
    depends_on: 
     - mongodb
  app2:
    image: node_app
    container_name: app2
    ports:
      - "3000"
    environment:
      DEBUG: 1
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017 
    volumes:
      - ./app:/src
      - /src/node_modules
    command: npm run start
    depends_on: 
     - mongodb
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "8000:8000"

